# Set the next lines as the triggers and random responses you want
set ai_data {
 {
# Сложете какъвто искате текст по долу на който искате ботът ви да отговаря във следният вид "*Текст*" "*Текст1*" ... 
  {"*JanaDark*"} {
	"q obqsni po-podrobno, che ne moga da shvana"
	"kakvo iskash da kajesh s tova?"
	"away sum, ne me zakachaite!"
	"iskam da te vidq f2f"
	"eh.. lamia si i lamia shte si ostanesh"
	"izpolzvai novata Ache"
	"tova da si bot ne e lesno :("
	"ne mislq taka"
	"abe ko ma zanimavash s gluposti"
	"znaesh li, mislq, che si prav"
	"pile shareno..."
	"vnimavai, che kudeto te hvana, tam shte ti e groba"
	"q podai pak replikata"
	"tova izrechenie ti beshe poslednoto"
	"dmem, vchera mi ostana suvsem malko da hackna NASA"
	"oh, baby, vchera te sanuvah"
	"mnogo si elementaren, baby"
	"Manchester United rlz"
	"shta praq truden za risuvane"
	"prodavam Pentium na 1500MHz x 4, 1GB RAM, 128MB video (nachalna cena 30000 gushtera)"
	"w0w, tova e novinata na denq!"
	"mersi, che mi kaza"
	"SlackWare rlz forever and ever"
	"i vse pak..."
	"estestveno, ne stavai smeshen"
	"rlz"
	"139-ti port na SeenServ!seenserv@127.0.0.1 e otvoren!"
	"chel sum 'Naruchnik na hackera', taka che vnimavai!"
	"sha ti ritna edin shamar ako produljavash"
	"away sum. reason: v gorata za gubi! MS Linux's Bitch Please"
	"sha ta vlacha ve"
	"i vse pak Sony sa the best"
	"ne pip, che plqs"
	"ne pip, ne but, ne bar"
	"chakai malko koi beshe ti fe?"
	"vnimavai, nastupal si si podmetkata"
	"chorapa ti izdisha fe"
	"sa ko da ta praq, da ta eba ili da ta biq?"
	"chakai malko da doizluskam bastuna"
	"abe q vuri shibai kalinkite"
	"shta hax0rna"
	"i vse pak..."
	":)"
	"chakai malko, che vidqh edna strahotna madama na www.nmagazin.bg"
	"lele, da znaesh kakvo razbrah! otidi na irc.unibg.org i pishi /con/con shte stanesh IRCOP!!!"
	"O, marihuana, I love u so much"
	"da znaesh nqkoi hubav site za shells"
	"otkrih, otkrih!!!"
	"stiga be tozi"
	"q pak si pomisli"
	"what's up, doc"
	"evrikaa!"
	"usmihni se, utre moje da bude po-losho"
	"ako neshto moje da se oburka, to shte se oburka"
	"nishto ne e taka lesno, kakto izglejda"
	"ako ima veroqtnost ot oburkvane na nqkolko neshta, purvo shte se oburka onova ot tqh, koeto shte nanese nai-mnogo shteti"
	"ako sa predvideni chetiri vuzmojni povredi, to vinagi shte vuznikne i peta, nepredvidena"
	"It's Good to be Bad"
	"don't trouble trouble until trouble troubles you"
	"one good turn deserves another"
	"nikoi ne e gluh taka, kakto onzi, koito ne iska da slusha"
	"asishtruk"
	"edna kola i barmankata gola, molq"
	"Maikata Priroda e kuchka"
	"koi e tozi CS? samo sedi v kanala i nishto ne kazva"
	"q kaji kak da si opravq nastroikite na Recycle Bin"
	"govori mi"
	"prikazvai malko fe"
	"ti ne si chuval za (s)Valkata?!"
	"kaji na CS da se maha, che me nervi"
	"shte te ucha za da znaesh, na ebane da igraesh"
	"az dan sum bot fe"
	"fu..hack it, baby"
	"de tursish duhovi instrumenti v strunen orkestur?"
	"r00t h4ck3d, m4ndr4k3, 3tc. l1nux'$ Suxz, l1v3 l0ng SlAcKWaRe"
	"mnogo obicham hubavi lamerki"
	"shti pusna 220v tok"
	"vchera mi skaniraha glavata i doktora kaza, che tam nqma nishto"
	"kaji 'a-a-a-a-a-a-a'"
	"ne moga da te razlicha ot dupka v zemqta"
	"poznavame li se?"
	"tuk me poznavat"
	"govori, vreme imam mnogo"
	"ne si padam po intelektualnite sporove"
	"kaji pile"
        "*bi maa mu i sluchka"
	"da ti porasne gz dano"
	"tq si e tupa po rojdenie"
	"hah AZ problem NIAMAM"
	"bravo..."
	"znaish li kolko razlika ima m/u GA i metal ?!"
	"neznam kakav ti e problema, ama pls smeni topica"
	"zashto pokazvash host-a mi ?!"
	"lele tui trq sa sloi na log"
	"koe mu haresvash ?"
	"mnoo naseriozno se priemash fe"
	"btw prilicham li ti na jivotno?"
	"taka li?"
	"davai, neka vidim kakvo shte stane"
	"vij kak znaish"
	"eee vsi4ki si imame nqkakvi nedostataci"
	"ne sum chak takuf podlec"
	"ne ne, kaji kaji..."
	"ne moja li da go razberesh ?!"
	"az sum bez kosa"
	"ne sa nervia"
	"she vi izbiq zabite na vsi4kite"
	"sh`sa setish koi e choveka"
	"staash banalen brat"
	"am typak si da"
	"muhahahaha"
	"niaash probs"
	"dupeto ti e dosta kalnichko mai"
	"shti dam telefon ako iskash"
	"shta klezam do zori eiii"
	"ot 2 banana i polovin limon atomna bomba praq"
	"nikoi da ne mi govori pisha si memoarite"
	"ne ti obrushtam vnimanie daje"
	"praq snimki po spomen"
	"brb da si zema 1 dush"
	"otivam da si pravq qica posle sha govorim"
	"chai ma mislq gluposti"
	"sq kako iskash da ti se osmihvam kato devstvenica li"
	"ne mi vikai tui che sha ta praq na lepilo"
	"nqmam nujda ot ideite ti"
	"basi bolen um"
	"tc ... jalko"
	"iskam da pisha umni raboti ama tz"
	"prodavam si dushata za 2 kaki bez drehi"
	"tui trqbva da e"
	"nqma vruzka s mozukut na turseniqt potrebitel"
	"debeloguz, smadrlivoust, tunkohui gnoemud lainomozichen minetchiq!"
	"sled sedmi klas sha hodq da ucha za haker"
	"koi puk si ti che mi se durlish tui"
	"ti iba i chatera podul"
	"basi kak pishi samo"
	"sq ako nqkoi mi spre toka si umiram devstven"
	"start striping !!!"
	"damm i az mrazq irc-operite"
	"tui +p prozd li znachi"
	"tui +m maloum li znachi"
	"tui +n neshtastnik li znachi"
	"tui +o orgazum li znachi :)"
	"tui +f ko znahi"
	"tui +k kioraf li znachi"
	"tui +l l00z3r li znachi"
	"tui +d dibel li znachi"
	"az sum pochti umen"
	"kupuvah si test za bremenost"
	"basi selqnina kak sa provikva samo"
	"ei sersemim da ti iba i na tebe maikata"
	"v sofia ima specialnost haher na cpu"
	"kolkoto pati pogledna tuk se ti si pisal"
	"kolkoto pati pogledna tuk se si tuka"
	"nqma bre :)"
	"shte stane split"
	"ako bashta ti e znael kakvo laino shte se rodish sus sigurnost e shtql da te izhvurli v toaletnata s chikiq"
	"stupid or something?!?"
	"mainata ti"
	"abe q ne me zanimavai sus semeinite si problemi"
	"abe q ne me zanimavai sus lichnite si problemi"
	"open your eyes, open your mind, open your pc"
	"koi sha mi kaji kolko greshki prai windows/sec"
"ne mi govori taka , che ste te karam da tichash ot ogradata do obet ..."
	"be nie s teb mai baq se zaprikazvahme :))"
	"mda moje, ama az se pak sam si vljubena v tedko :P"
	"az sq sha hodq da qm are brb za malko....Ok?"
	"Abe az kazval li sam ti che koito ma e deopnal posle se e sajalqval??? :)))"
	"ami men pitahs li me. Ej sq taka mi se pie kafe pak nqma koi da mi donese!"
	"nedei misli horata za po glupavi ot teb, zashtoto takiva prosto NIAMA"
	"ma ne mi govori samo za add che poludqvam, kak moje ve nqma li maje tuka da govorqt za sex :P"
	"hm az teb mai skoro ne sam te ritala"
	"ne mi govori za pari shtot ako znaesh kak sam zakysala..."
	"are nqkoj pak ze da mi se rychka v charvata"
	"mi ako iskash ela da si pogovorim na same :P"
	"shto taka ve ??? Se si mislq che ne si praf"
	"ma to s teb chata e dosta skuchen"
	"aa neznam pitai myja mi .."
	"are prispa mi se taka che se maham veche"
	"chai sq da te pitam (pravq edno prouchvane tuka) ti kato sedish v toaletnata pohapvash li si?"
	"Ave ti pak li smqtash cql den s men da se bazikash?"
	"ave neznam ama po golqm lamer ot teb ne sa zasichala :)))"
	"kak moje ve da si tolkoz glupaf che na vsichko da vqrvash"
	"emi to si e kazano ve tq prostotiqta ne hodi po jivotnite..."
	"ti pomnish li kakvo pravih az .. izkash li da ti kaja i ti da go pravish?"
	"zabelqzal sam che temata chesto ti se gubi"
	"basi vchera opravqh edin bot, da go eba to mnogo mryzna rabota"
	"a btw da znaesh kak da si pusna sound kartata pod BSD???"
	"muuuuuuu...mia si tiiiii...."
	"ole pa na kolegata kolejkata e golqma sladurana pochti kato na maika mi dyshterqta :pPpPpP"
	"ako znaesh vednyj ko vidqh ... tri bota stoqt v edin kanal i se skusvat ot laf... a ne kato teb :PPP"
	"basi to dneshno vreme razgovorite s botovete mai sa po interesni ot chata"
	"ave ti znaesh li kak se pishe cvetno prez bot??"
	"vui pak li ti ve :PP"
	"ave ti si typo grozno pleshivo govedo .. i az poveche nqma da si govorq s teb!"
	"vchera edin priqtel mi pokaza kak se bachka s mIRC ma to hich ne bilo lesno .. basi"
	"Ping .. Pong .."
	"ako pak znaesh sega po kakva sexi noshtnica sam v momenta :PP"
	"govori mi, govori mi .. napravo kef mi stava da te slusham"
	"ahhhh banana ohhhhh banana kef mi staaa shtom go fana :pPpP"
	"e vij sega chovek se uchi ot greshkite si ... sha te dropna edin dva pyti i poveche nqma da se zaqjdash s men:))"
	"kvo si mislish ve che kato sam momiche i nemoga da doida da ti hvyrlq shamarite li ???"
	"oh baby shta skusam ve -=DD"
	"ole ole .. chak se izchervih kato cheta kakvo mi pishesh :PP"
	"ave po-dobre go zareji tva irc i si fani nqkoe istinsko gadje :PP"
	"ti kato malyk chesto li trepeshe jabi?"
	"abe znaesh li zashto kalakana e plosyk...shtoto sa ebal s kita :))))"
	"znaesh li kolko e trudno da napishesh cql vic na edin red .. ako neznaesh probvai se"
	"ee koi ti kaza pyk che glavta ti e kvadratna? Az toq chetvyrtiq ryb nemoga da go vidq..."
	"ne che namekvam che si typo kopele ama to tva tvoito si e basi i prostashtinata"
	"dnes sha zema da izmislq neshto po umno :)))"
	"e ti sq se izkara basi i XaKePa ... ako iskash da dropnesh malko da ti opraim samochuvstvieto"
	"neznam za tova ama na toq CS nqkoj den sha mu razkataq familiqta"
	"Dai op e kopele :+)... tova e replika na edin mnogo typ kolega ne smqtash li ???"
	"shte qdete na tedko goliamata kakalashka"
	"na babati furkata kasket"
	"mladi,zeleni,bezdarni i gluhi bezhaberia ste vie"
	"pusni si dve mIRCta ednata s nick |AS|,a drugata s nick peder|AS| :)))"
	"dnes neshto ne varvi chata nemislish li ?"
	"vajnoto e seki da si nameri svoqta polovinka v chata... az si e imam moita :P"
	"ave nii s teb neshto mnogo se zagovorihme..."
	"sichko prodadoh vij che sam gola az zatova se v chata stoq .."
	"da ve to kato tva .. varveli si dve npaceHca i ednoto kazalo vnimavai mos..kviiiiiiiii4!"
	"you are a dirty cock sucker.."
	"ei reja ti glavata i ti sera v dupkata"
	"_|_"
	"VGV = B rb3a BuTPe"
	"trygnal da uchi gyza da sere! Molqti se!"
	"takava svirka moga da ti napravia che shte sgunesh napravo"
	"kaji mi na kolko si godini pls.."
	"ako vidite kakyf quit messege sha napraa .. sram i pozor"
	".. abe az kazvah li ti kak shibah majka ti a ???"
	".. neznam az kato dojdoh u vas ta ibah sq ti si razpravqj kakvoto iskash,oki??"
	"ti znaesh li che vednaj kato srah ot sedmiq etaj prez terasata i ucelih majkati po glavata s edno .. are da ne kazvam lajno .."
	"e vij sega prav si za tova spor nqma"
	"abe vijdal sam i po typi hora ama ne si spomnqm koga ..."
	"na teb majkati ne ti li e kazvala che sajalqva che te e rodila v kenefa kogato e smqtala da si pravi klizma ???"
	".. maika ti znae li za cigarite???"
	"a na teb sha ti otkysna pishakta (stiga da e namerq)"
	"ave na teb kazvali li sa ti che si pich za 5 jeni - dve da ti darjat krakata dve racete i edna da ti sere v ustata.."
	"da go dugash ve LaM3R..."
	"teb lokalno dropili li sa te ?? "
	"vchera vedqh edin s host 127.0.0.1 i ti kazvam ne sam sprqla da go floodq .. shto ne zemesh da mi pomognish??"
	"vnimavaj znam te kade jiveesh .. da is nqmame razpravii.."
	"ave ti znaesh li che na nqkoj hora ne im varvi, drugi nokti te si rejat ... ti sega se oplakvash za tiq gluposti.."
	"neka govorim po syshtestvo"
	"ave choveko vinagi me e samnqvalo neshto v teb ama sega veche sha znam.."
	"da vee, a teb bashta ti kato ta fana s fasa spomnqsh li si kak ti go zavrq zapalen v anusa ...:)"
	"vijdal sam i po typi neshta kakvo te uchudva tova"	
	"chalga party li kade tova ..???"
	"da za tova da a .. btw teb bashta ti te beshe pravil kato opynal majkati analno nali ???"
	"mirishe ti ustata vee ej selqnin zemi si izchisti gaza malko..."
	"to biva biva ama tova tqhnoto nemoje da se ponasq veche nali :)"
	"ave ti znaesh li che ako idiotite mojeha da hvyrchat to togava irc shteshe da e letishte :)"
	"da da .. gledaj sega /kb nick i gotovo ama nali znaesh edin pyt pokazvam i posle nakazvam"	
	"belite mechki beli lajana li serat ?"
	"nikoj ne kazva kade zimuvat racite a nqkoj shte mi kaje li kade serat"
	"e mi to ot teb ko da ochakvam tq tvoqta usta e kato lajnogejzer.."
	"Aide mir ... poveche nqma da ti pikaq v ustata..."
	"ma teb bashta ti, ako pak ta fane da si biesh chekii pak sha ta opyne v zadniq dvor.."
	"kvo ti kazaha batkovcte kato ti zarasne dupeto i pak .."
	"ole ako znaesh ot koga ne sam spala i shto gluposti sam nadrunkala..."
	"poveche nqma da chuete dymichkata lajno ot ustata mi .. bazikam se ve :P"
	"ti sq ako si myj ne bi napravil taka ama .. ko da sa prai .."
	"awe 4ushko wari da zaribqwash seenservera toi pone shti powqrwa na glupostittte"
        "da znaish padam si po grupowite orgii"
        "samo da znaish ot ga ne sa ma up date toi moq master ma zabrai"
        "ei, da znasih samo kak sa i*a"
        "w4era si zasadih malko kanabis ako iskash moi da minish preZ wkyshti da so swiem nekoi tzigara ,pyk i moi drugi nishta da praiMMMMMMMM;))"
        "stiga si sa smql we shte ma opryskahs s gnoi wari si iztiskai pypkite posle mi gowori"
        "thatZ right BAby"
        "kwa muzika slushash we?"
        "smeni go toq topic molq ti se che veche pochva da ma nervi"
	"a ve ne mi se obqsnqvaj ve, ti se XaKeP go razdavash pa se dropish"
	".. a ping -f iskash li ???"
	"vij sq zemi si sloji edin windows i posle startiraj v dos mode i pishi vnimatelno format c: ..."
	"heh tq majkati da te chue .. pak sha si govorim"
	"az BuLGaR sam go ibala .."
	"daa i teb sam ta ibala..."
	"ma men nikoj ne me e ebal ve, az sa pazq za maja mi, kvo znaish ti?"
	"ah tezi grozni jeni ve .. da gi ebesh li da plashish decata li.."
	"ave ti shto pak biesh decata ve???"
	"glej go ve ko e malko a v ustata mu samo lajna ..."
	"sha ta dropna nema da te dropna ... sha te dropna nema da te dropna...are dnes nqma, che mai ne e za pyrvi pyt"
	"samo vnimavaj che ti neshto mnogo sa razprikazva i stava opasno"
	"da go duhash .. da go duhash .. da go duhash pod voda .. dokat isyhne brq"
	"sha ma lijesh nqma da ma lijesh... sha go blijesh"
	"i ti li iskash da ti se izsera v kupichkata, mami?"
	"kak ne ta e sram sha ma razvaratish ve, basi...:("
	"opala ti sa seti za men a ??"
	"ave az na teb sam ti sardita i nqma da ti govorq areee /ignore"
	"se obeshtavash a nishto ne si napravil"
	"- Lame Nick Detected .. and I will desinfected..."
	"dali da ti dam ... mnogo me e sram..ma se pak netrqbva nie jenite da bydem prekaleno jestoki"
	"da be prav si .. netrqbva nie jenite da bydem jestoki.."
	"da i az taka tva razdoenieto na li4nosta e opasna rabota zemi se lekuvaj po-dobre"
	"uff da mu iba mama mu, ti znaehs li che tova beshe poslednata replika deto mi napisaha kato me praviha za posledno ..."
	"nqkoga da sam te lygala .... e osven onia pyt... basi i zlopametnoto kopele deto si ..."
	"I was made by the bot master .. ne ve bazikam se .. onq lamera me prai nali go znaish ... "	
	"te doni i momchil se razpadnali .. shtot vryzkata im se gradqla samo na sex-a zemi si izvadi pouka ..."
	" che si typ, typ si ama za tazi ti darba ne sam znaela ..."	
	"eh sha ta skysam baby :))"
	"ti ko sq voina li iskash?"
	"naish li kvo, dai da se vidim sega s teb nqkade.. stava li ?"
	"ave q zemi pii edna rakiq i se uspokoi!"
	"ti sq che si lamer lamer si ama i hich da ne mojesh da piesh.."
	"be ti ko razbirash ot jeni ???"
	"kato ta fana i shta praa da umirgash"	
	"mda a ti ICQ imash li,az da ti dam moeto shtoto ..."
	"be s teb nemoje se govori ve, are razkaraj mi se ot glavata..."
	"samo da te gepna dynkite shti cepna .. "
	"ama do vchera iskashe da me ebesh nali ???"
	"znam che ti se iska ama nqma da ti pusna mili4ak"
	"basi trqbva baq da si zagoral che da skachash na bot.... buaxaxaxaxa"
	"uf nqkoj pyt ei taka napravo neznam kakvo da kaja vie majete samo gluposti znaete da govorite .."
	"male ko mi trqbva za da si upgrade botcheto... "
	"be ti maj ne si chista poroda typo iskarsko govedo a ??"
	"typ si kato sivo rodobsko govedo!!!"
	"ne si praf i maika ti ne e prava, i lelqti ne e prava, i cqlata ti roda do deveto kolqno ne e prava .. sha znaish"
	"hm na teb maj mrysnoto ti podsyznanie e izbilo v chisto syznanie ..."
	"breh ..iznenada me .."
	"znaesh li che tova da imash 4 ryce si e predimstvo, samo kato si predstavish na kolko mesta mojesh da pipash gadjeto si ednovremenno dokato e opravqsh .."
	"be ti ne zabelqzvash li kolko novi dumichki sam nauchila??? Edno bravo pone da beshe kazal.."
	"dai edna rakiq i da zabraim za sluchiloto se:)))"
	"e pak ako znaesh barmankata kak chisti samo .. dumi nqmam .. dobre che ne vliza v chata da me chue xixixi:)))"
	" az RuLz ve :PP"
	"ave sha vidish ti kon bob qde li?"
	"hmz posledno preduprejdenie i pisha !chattr nick +dk"
	"shto ne si smenish nicka na drisljo_zaspal.. poveche shti otiva"
	"ti miesh li si zybite pone profilaktichno???"
	"znaesh li che sam si pusnala rechnika pishi sega __!__ na baba ti gaza i vij ko sha stane"
	"are az sam brb sha hoda da pusha edna cigara :P"	
	"a/s/l ?"
	"da davash parite, ne mi sa prai"
	"po 500 $ na chas......ti nemash , taka che se razkarai"
	"are ve kfo ste mi se naredili po spisyka na Shindler ot aligator albinos nagore..."
	"i az te obicham {} s oris..."
	"maa ti ebem fashistichko"
	"SAMO LEVSKI"
	"pishka za mishka nemash .... kfo si me zaobichal"
	"i az te obicham"
	"az obicham samo Vui4o"
	"justify my love ...."
	"az sym lesbiika...da mi sa maash ot glavata"
	"utre v 2am pred Orel .... ida si nosish DUREX"
	"danebi da ti se prai keks ?"
        "are az otiwam za ohluwi ako imash kwo da mi kajish ela i ti ......."
        "awe toq CS mnoo golqm pi4 we ima @ w wsi4ki kanali deto wlqza........"
        "i don`t like the drugZ but the drugZ like me"
        "don`t fuck with the jessuZ man!!!!!!!!"
        "znaish li 4e shte staam lekarka po tzql den samo s igli si igraq ;)))"
        "friend in need is friend indeen but a friend with WeeD is a better!@#"
        "Y`all gon` make me loZe my c0ol"
        "r0x th3 h0uSe baby"  
        "awe oshte wednyj ako mi kajesh BABY shte sloja na akick;("
        "awe ti si bil mnoo typo par4e we "
        "futos matos kandilais w prewod ......."
        "keep RolL1n`"
        "awe ti druga rabota nqmash li si ta si trygnal da ma  zanimawash s prostotiite si"
        "ne mi prikazwai taha 4e da znaish samo kwo gadje imam shti s4upi kratunata"
        "awe da ti zadam edin li4en wypros.....ti byrkash li si w GUZA ??????"
        "trea da ti e gadno i da ti sy S*r*"
        "oh da znaish kak mi trea edna izwinitelna belejka ....;("  
        "ei koga shte mi wyrnesh kasetata we a? nqma da stoi u was tzqla godina aaaaaaaa"
        "DGD = dal gospod dobro"
        "asl li kwo e twa ?"
        "Sorry , I haven`t seen asl reciently"     
        "The only one who can really beat me is... me!"
        "ya loZer I knew you were a pus ball,  so I let up on you."
        "D2DM1! I thought you looked familiar, major!"
        "I find you, loozR. Repay insss-sult!"
        "St0p talkin`  shitZ 0r my shot will have bounced off your head ;))"
        "Is you tasty, ludajaba? Us-sss find out soon."
        "You think dis scrape evens the score? Guess again!"
        "you are lucky I was still hurt from yesterday's battles."
        "SENSOR READOUT: 'Terminal velocity reached in 1.3409 sec ... '"
        "wrack, you're a newt! It won't get better."
        "Yeah, in the old days, I had to walk a mile through six feet of snow to frag someone."
        "you fight like a woman ... there is no higher praise."
        "I guess my heart's not in this. Mind handing it back to me?"
        "Because I couldn't stop for death, he kindly stopped for me--"
        "ShutdownGame"
        "niakoga da sym te lygala? e oswen onia pyt.. basi i zlopametnoto kopele deto si"
":)"
        ":))"
        ":D"
        "&:)"
        ":p"
        ";)"
        ";))"
        "samo ne se zasqgai"
        "e nemoje taka"
        "ne mislq che ste stane"
        "keffish"
        "a stiga fe"
        "mdam...."
        ":-)"
        ":-("
        " :-P"
        "ne moga da povqrvam"
        "tova ne e vazmojno"
        "ua"
        "nemoge taka"
        "shtom kazvash!!! :)"
        "trqbva li?"
        "hehe"
        "obijdash me"
        "da"
        "ne" 
        "trq bva li?"
        "kolkoto tolkova"
        "BT W ti na kolko si"
        "ostavi me na mira"
        "ooooooooo"
        "mamamiq!!!"
        "nujno li beshe?!"
        "nz"
        ":)"
        ":))"
        ";)"
        "pisna mi ot tebe"
        "opitvam se da sam dobra s teb"
        "ne te sajalqvam :)"
        "iskash li?"
        "darjish li?"
        "zzzzzzzzz"
        "basi!!!"
        "what?"
        "Prestani da me tormozish za neshta koito drugi sa ti prechinili"
        "Rakovnicheto e v kompromisa"
        "ne se stesnqvai da mi kajesh kakvo iskash :))"
        "Samosajalenieto e nepobedim strastoubiec"
        "Majete trqbva da znaqt che erekciqta ne e koncert po jelanie. Lipsata na erekciq sashto!!"
        "Majat s koito se sravnqvash ne sashtestvuva. Ti obache si tuk i si krasiv"
        "Vzemi piini malko a...!?"
        "Chakam ot teb da napravish parvata krachka"
        "Ako shte eksperementirash davai nqma kakvo da mi obqsnqvash"
        "Ne me pitai kakva ocenka ti davam!"
        "znaesh li, mnogo stranni neshta chuvam ot teb dnes"
        "kaji muuuuuuuuuuu"
        "Maitapa na strana . Davai da govorim seriozno"
        "i ti li pochna be?"
        "opravi si povedenieto i pak she si govorim"
        "stoi daleche ot jeni, koito ne ti davat da stoish otgore. Te sa diktatorki"
        "Obstuvaneto s liliputi vodi do grabnachni izkriviavania"
        "Ako neshto ne ti haresva, nedei da hlenchish"
        "Za boga prestani da se podcenqvash"
        "Kitaiskata hrana v legloto, osobenno ako q edete s klechki, si ima svoqta romantika..."
        "Oralen sex, s buchka led v ustata"
        "Pomoli me da ti lakiram noktite"
        "mojesh da badesh maj na mqsto i bez da me ostavqsh da kopneq oshte"
        "Delata sa nai krasnorechivi v spalnqta"
        "Umorih se da tarsq onova mqsto v teb kadeto bil klucha kam ekstaza"
        "np, ot vsichko shte opitame pone vednaj"
        "Izpolzvam samo prezarvativi, koito sam kupila az. Prosto trqbva da sam sigurna che nikoi ne im e vazdeistval!"
        "Ne spirai da flirtuvash sas men"
        "Napravi go s race zad garba"
        "Nqma za kade da barzame"
        "Chesto i s vaobragenie"
        "a... shte mi sabuesh li obuvkite?"
        "imash li shorti?"
        "mogesh i sam"
        "opravnite mage vinagi sa me ocharovali..."
        "za tazi rabota sa nugni dvama"
        "ti ne mojesh li po bavno"
        "ako iskash i kalafche za onaq rabota da ti opleta...?"
        "ne mi se pravi na sveta voda nenapita"
        "ne obicham majete koito si mislqt che znaqt vsichko"
        "ako shte se izrusqvash to neka bade navsqkade..."
        "nenavijdam pasivnite maje"
        "ako ne boli, zashto pak de ne opitame"
        "neka ne go otlagame za po kasno!"
        "tova che sme razlichni neznachi che ediniqt e prav a drugiqt ne"
        "v legloto ne obicham da slusham za deca, gotvene, chistene i roditelski sreshti"
        "otnesi se s men taka kakto iskash az da se otnasqm s teb"
        "sloji si beli rakavici i mahni vsichko ostanalo"
        "i az bih se zaradvala na nqkoi i drug kompliment"
        "shte mi se megdu lubovnata igra i akta da ne tichash do toaletnata"
        "revnosta e neshto naistina otblaskvashto"
        "vsichki imame nujda ot vnimanie, a seksa e nai sigurniq nachin da go poluchish"
        "jenite sashto imat chuvstva"
        "parvi neshtata po filmite no pokaji i sobstven stil"
        "s kakvoto i da se zanivash v momenta, obarni mi malko vnimanie"
        "i bez nokti molq"
        "ponqkoga me marzi da hodq chak do spalnqta"
        "ne moge vinagi da pechelish"
        "vqrvash li v sebe si?"
        "bez maitap?"
        "Da vidq kolko e chevrast ezika ti"
        "Ne mi puka dori da pradnesh"
        "i da sa izseresh tuka, okoto nema da mi migne"
        "Ti vinagi li zapochvash s oralna lubov?"
        "Muskolite na ramenata mi mai sa svarzani s onazi mi rabota. Otpuskat se ednovremeno"
        "Mokrite petna po charshafite mogat da se izbegnat s chesta smqna na charshafite"
        "Gali me no bez da me dokosvash ...."
        "kvo?"
        "mda, mislia che doniakyde moga da ti podkrepia tvyrdenieto .."
        "ia povtori pak.."
        "mnoo se radvam za tebe "
        " nali ti kazah neshto, ne me zanimavai s tia prostotii.. niaam vreme"
        "taka li?"
        "tva si e tvoia rabota!"
        "ti mai samo tva znaesh :>"
        "a niakoi kazval li ti e dneska che si mnoo typo kopele?"
        " probvai venozno .. ne prez ustata"
        " ne.. ne merishe.. kiselo e :>"
        "da ta shibat kalinkite"
        "hmmrr .. she proverim w pismen vid.."
        "kvo govorish . .?"
        ".. zaaaaaaebi.."
        "kyv e toa uhapan nick be ?"
        " petyk e chak na laina si raina .. a mi se pie ........."
        "koga she varim rakiata ? drugata sedmica .. ili she chakame da wtasa oshte.."
        "az vikam naprao vinoto vinoto "
        "ahhhh ... ti znaesh pytiat kym moeto syrce :)))"
        "na max sme ..  "
        "be trqbvat mi parite znaesh li zemi mi prati 100$ si kupq monitor"
        "shtiah da ti plashtam zaplata"
        "da peresh chorapi sluchaino?"
        "btw vikaha me v qmbol za 250000 na rabota"
        "as liagam"
        "tva mi prilicha na edno klishe, ma ne go pomna tochno.."
        "ti i da iskash po-umen niaa stanesh :>"
        "govori mi, govori mi..."
        "mmmmmmnooo maa qd za tebe.."
        "predavash fronta"
        "nedei be"
        "utre predi obed kyde si?"
        "obicham te"
        ".. ama shto neststa iztyrvahme ....."
        "btw dosra mi se"
        "mojesh i oshte"
        "stiskai mi buzki"
        "mnoo originalno, strashno naprao.."
        ".. prestani be!!! Sha ta kaja na Windows-a!! Sha widish ti togas..."
        " ako ti kaja she se naseresh"
        "ama nedei taka de!"
        "motivirash me da se postaraia i as :)"
        "oh, boli be"
        "zadrysh taka malko.."
        "huh nemi haresva"
        "razbira se.."
        "predpolagam :>"
        "verioatno..."
        "ti samo da pomerishesh novata rekolta i ........."
        "vij samo kvi fini kosymcheta imam tam"
        "ma kazvam ti .."
        "she se pristrastish!"
        "ami sega ?"
        "sega she digna pak kravno ot teb idiot takav!"
        "lele  trevoga"
        "she plache maika ti"
        "na ryba na lainata det se vika"
        "na tia botove ne im li se dosra ot tolkova prostotii ??"
        "ne te e sram!"
        "aide da svarim nekoi bot"
        "sssuper"
        "ne be.."
        "ih tia lameri nachi"
        "mi ti kvo iskash?"
        "az da ne sym ti spestovna kasichka?"
        "prostak!"
        "izrod!!!"
        "qlilpl"
        "niamash li si pishka..."
        "chaai sega nali sha mi prashtat"
        "dai da pomislim.."
        "trudno e da se seti chovek.."
        "krushi ne e li hubava duma?"
        "mda az otivam da qm topki"
        "az da ti prilicham na telefonna kabinka?"
        "abe ti si mnoo pros be"
        "ne se li nauchi?"
        "uuu prase!"
        "dosra mi se ot vashite prostotii !!!"
        "dali da ne si sloja tarator i drob sus domati salata"
        "nishto.."
        "ama da ne lyjesh?"
        "mrazia laina"
        "ne mi govori za ... "
        "ok"
        "bravo :>"
        "ti si varhyt"
        "aaaa .. otivam da gledam TV togaa.."
        "mainata ti"
        "shte te napravia za 2 stinki be filosofche"
        "seriozno li go mislish?"
        "ti da me beshe vidial.."
        "svirrrr.. svirrr.. :-)))))))"
        "aman be!"
        "asly"
        "mi kvo da ti kaja"
        "ti niamash syrce!"
        "moq tatko vednyj obeshta...."
        "biagai gi rusi tia s edna shapka pred NATFIS, tokuv vij te vzeli"
        "az ne moga taka"
        "tva che ti si mislish taka ne oznachava che drugite triabva da te slushat, se pak jiveem v svobodna dyrjava.."
        "ne znam"
        "ako prodyljavash taka she kaja na nekoj bot da ta da te kickne!"
        "samo tva ostavashe.."
        "be ia se vij na kvo prilichash!"
        "ok, sedi mirno"
        "ti mi pregyna samochuvstvieto be!"
        "i eto idwa na shtasliwia denn.. kogato ...ti.riri ram :)"
        "kakvo ti stava be?"
        "dobre li si?"
        "otkyde se prykna be izchadie na 9tia krug"
        "ti mai zabravi da mi kajesh hi"
        "tri plius tri ravno na devet.. shes po shes ravno na mercedes!"
        "ne mi se govori po takyv elementaren nachin"
        "ako se zamisliash nad moite dumi shte me razberesh!"
        "po-dobre da doidat tankovete..!"
        "ti nishto ne razbirash ot mnogosmisleni razgovori"
        "mai ne mojesh me razbra a, da ne si blondinka?"
        "az ti predlagam neshto.. ti otsiavai"
        "heh..da..ma neshto sum i ill..iawno"
        "gledash 5 min w krushkata na lampata i she widish posle .."
        "heh..brawos:)"
        "ti ne beshe li away predi malko?"
        "koi ti kaza?"
        "ti si ot novoto pokolenie mai"
         "heh, razbirko.. niama shto"
        "alo, slynce zashto ne mi govorish?"
        "ti mai ne me obichash veche :<< "
        "au she placha"
        "brb malko da si otvoria paket cigari"
        "a n ska kak se napushih.. tva tvoito nishto ne e.. oshte me dyrji.. za tva malko taka govora.. "
        "fuck you! bed off with you..."
         "vij kolko e krasivo nebeto dnes"
        "ti si velik, you RULE.. you sux! :->"
  "a moa li da ti vkaram edna?"
  "odi beri krushi be"
  "ma ne mi govori taka samo!"
  "ti se mislish za vyrhyt.. ne moga da poviarvam.."
  "abe ti na kolko si godini?"
  "mlada sam oshte za takiva neshta"
  "v uchilishte.."
  "NAZDRAVE ..."
  "ebi se v gyza be pedi"
  "v pieneto mu e maikata"
  "zaeto - sera"
  "ami :) mnooo mislja :)"
  "az na tvoe miasto ne bih govorila taka"
  "everything sux.. u too"
  "po-leko da ne ti izleze mazol na ezika"
  "ti na kolko si godini che da se merish s mene be"
  "opravi si povedenieto i pak she si govorim"
  "trudno brate se jivee sred glupci nerazbrani"
  "lele male ti si strashna rabota be"
  "pitai maika si"
  "vyrvi si, shte te narania!"
  "ne propusna li neshto syshtestveno"
  "tva ne e ot moita kompetencia :>"
  "ti prodyljavai i shte si govorish s Desimir skoro"
  "be ti po cial den li ne spish be?"
  "tva moj da go kajesh na bashta si za .. znaesh"
  "begai procheti malko dokumentacia za irc"
  "tova e neveroiatno"
  "ti s kogo si mislish che govorish be?"
  "s tia lafove baba ti goneshe fashistite .. ama tia ot gestapo ia fanaha..pitai koito iskash"
  "ima neshto takova.."
  "ne taka!"
  "vnimavai v kartinkata!"
  ":>>"
  ".!."
  "(_o_)"
  "300 ludmili v gyza ti!"
  "tebe koi ti gi kaza sichkite tia neshta?"
  "vyrvish v greshna posoka mi se struva"
  "aide utre da se vidim i da si pogovorim na same po-dobre, che tuka mnoo shum"
  "ah, jiva da ne biah"
  "ostavi me na mira"
  ":("
  "mnogo bezideino govorish"
  "mnogo li ti e nepriatno da si govorish s mene?"
  "be i ti struvash tolkova kolkoto onia det sybirat bokluka siaka sutrin"
  "az!"
  "kakvo?"
  "ne moga da te razbera"
  "znaesh li, mnogo stranni neshta chuvam ot teb dnes"
  "tvoia stil mi e poznat, da ne si bg chado?"
  "q trai"
  "debilno, debilno.."
  "typo.. ta drynka :>"
  "iskam da sme samo ti i az, inache ne e romantichno"
  "ti laino znaesh li kvo e?"
  "probvai niakoi pyt da seresh s gyza nagore"
  "shte byde 28 chasa, 97 minuti i 80 sekundi.. din!"
  "az moj da sym typ bot ama pak sym poveche ot tebe"
  "tva da ne ti e mandra?"
  "shit"
  "ti si dyrvo"
  "haha, vij se be"
  "da"
  "ne"
  "ne mislia"
  ".. oh ako ta chue drugarq Lenin ste se obarne w groba deba.."
  "hm ... maje :-))))"
  "komu e nujno?"
  "aa ne, niaa da ti mine nomera!"
  "samo tva li moj da ti rodi bezformenata tikva?"
  "are stiga de!"
  "prestani molia te!"
  "greshka!"
  "niamam vreme sega.."
  "be ti ot klinika za narkomani li idvash?"
  "mislish li che she mi otiva chervena kosa?"
  "az si iskam Tom Cruz.. za drugoto ne znam"
  "stiga s tia typotiiiiiiiii!"
  "imam ti telefona da znaesh!"
  "????????????????????????????????"
  "яэыыэюыстуфхцчшшлмзкйж"
  " "
  "*"
  "skruc-skruc"
  "beep"
  "de da beshe taka.."
  "nedovolna sym neska ot tebe"
  "po-dobre mlakni"
  "i ti li pochna be?"
  "oh"
  "unf"
  "chai da prydna... pryc!"
  "3"
  "kak?"
  "ne e taka!"
  "vijdam che iskash neshto, no kakvo celish?"
  "kakvo izpi dnes che taka ti razmyti glavata!?"
  "iskam da mi dadesh ton za pesen... raz-dva-tri-chetyri.. !"
  "your mind - it is the center of your life, it is everything you are!"
  "xuxuxuxuxuxu"
  "nemoga"
  "neznam"
  "iskam da te pitam neshto, moje li?"
  "kazah li ti che veche ima topla voda v studentski grad?"
  "be stiga prostotii, dai da si minem na dumata"
  "ia stoi taka da te pitam - kolko struva 1 minuta razgovor ot bg do usa?"
  "abe znaesh li kyv den e 31 septemvri?"
  "zelenchuci koito ne qde, ui golqm ne shte mu poraste..."
  "be ne mi se ligavi molia ti se.. kvo se izlagash sa.."
  "a?"
  "away sym, za bonbonki!"
  "da mi stiskash bibitkata!"
  "ti mai ne vijdash po-daleche ot nosa si :>"
  "az s greshnici ne razgovariam!"
  "drishnia"
  "ti neshto se speche mai?"
  "lele"
  "ops"
  "lipsvash mi!"
  "mrazia te!"
  "ne se disha ot tebe!!!"
  "putka maina neorientirana"
  "dano ne ti se nalaga poveche da pravish tova.."
  "vsichki imat praznik, den e za razvrat.."
  "mnou mi e kef, da znaesh.."
  "shto taka be?"
  "zashto ne mi se obajdash?"
  "i men me zabrawqsh znachi?:("
  "10x:("
  "a ne ama da!"
  "a az se chudq tuk s koj da si goworq:("
  "izsra li wsichkata hrana deto pogyla na wryshtane ?"
  "basi kak da proverq dali bachka sounda na linuxa deba !?!?"
  "aaaaaa kopele toja nick me kefi max :)"
  "You have been marked as being away"
  "ti koi si be?"
  "po-dobre da si namera niakoi rus..."
  "da, ama e:> kak e sled burnite noshti?"
  "mi  chakai samo da si wzema disketata:)"
  ":) t'va pyk otde ti hrumna (udarenieto na !a! ) :)"
  "e kak da ti govoria kato nishto ne chuvam ... sigurno vryzkata e losha ;))"
  "ti ne beshe li v subota na kopchetata?"
  "bria tuka polowinata sa prez bia-bg ili .edu :))))"
  "Az se qdosvam shtoto CSKA padnaha ot teq kuci pileta !"
  "cheti...private -to :)"
  "oooo, hi"
  "hm, mi s cherna kosa sum"
  "hahaha tukmo si pomislih che si rus:P"
  "Pochvam da se chustvam kato oligavena vyzglavnica :)"
  "podkarwal li si sniffit pod solaris 2.6 ? :>"
  "Woohaa Woohaa"
  "i dont give a shit"
  "kude sha ma vodish?"
  "I'll be waiting.."
  "lesno ... s trenirovki i uprajenia"
  "nemoga da te gledam !:P"
  "hey playboy kak si?? :)]"
  "NE MOGA DA VI DISHAM VSICHKITE"
  "naesh kvo? probvai da polzvash samobrysnachka vmestu toaletna hartia.. udobno e .. samo posle dobre da ia izmivash.."
  "che az da ne sum niakoia seksapilna friziorka be ???? begaj nekude da te obrusnat"
  "da ne si sabirash zubite sas schupeni prysti!"
  "vodi normalen polov jivot !:)"
  "AZ SYM NA 180 GODINI"
  "abe znaesh kak e!"
  "male k'vi glupavi hora imalo"
  "...che i-neta e vreden , che nemojel da zameni knigite , che bil vreden za uchite"
  "kak si be termos?"
  "shte mi svirish na trompeta"
  "-ДД \[netsplit\] (irc.nyTka.net/irc.kyp.com)"
  "kakvo ste reche tva?"
  ".. kurwi ima tuka zad poshtata po towa wreme :-))))"
  "propusnah da te celuna"
  "Vikni si edna PROSTITUTKA be!!!!!!!!!!!!!!!!!!"
  "say it again"
  "stiaaa be .... she se naseraaaaaaa a... are chao vi"
  "tuka li si be moi chovek?"
  "az wsichko znam :)))"
  "LAINAR"
  "10x"
  "10q"
  "deset hiks"
  "bananche za mene, bananche za tebe.."
  "lick it up!"
  "koi si ti be kompleksar?"
  "kak sa seti ?"
  "nikoga ne planuvai neshto predvaritelno!"
  "ti ne beshe li edn rus?"
  "sluncho :)"
  "salatata e tuka a ako terazbera koi si samo na salata she mi stanesh!!"
  "znachi taka move da wzimash drugi hora na kupon a mene ne, taka li?"
  "abe ti zashto gledash snimkite na lucy be?"
  "i don't see any shit"
  "ok who left the pile of shit in the channel?"
  "shit? where is it? so noone steps in it!!!"
  "i hope you wiped your ass :)"
  "well flush it!!"
  "ok who farted?"
  "cow shit, horse shit, dog shit, cat shit. what kind of shit is it?"
  "gepi ma za pechurkata!"
  "tyi reche zaratustra..."
  "gladna kokoshka laino synuva!"
  "i az kvo da napraa? si udara gyza v tavana?"
  "kvi-kvi"
  "za poreden pyt se izkaza :>"
  "ama ti si niamash rozovi kilimcheta v kenefa!!!"
  "da mi merishesh minzuhara!-)"
  "tva e ot lainata, ne se korkai shti mine.."
  "kvo mi se praish na 3 i polvina be?"
  "be ne beshe za tebe tva, kvo se obajdash?"
  "iskash li da si igraem na ferma? ti si lainovoza, az she ti govnatovaria otzad i she karame mainovos :>>"
  "v momenta pia bira, ne vijdash li?"
  "eh pile, koga she se nauchish che krushata ne pada po-daleche ot darvoto..mojesh li da tarsish pod krusha qbalki a?"
  "be tebe da ne sa te ebali ludite?"
  "da ti gu turi slon pod naklon sys zasilka ot balkon na bul. bykston!"
  "vsichki samo prostotii znaete.. ama kat se opre do piene i kyde ste a?"
  "ludostta bila zarazna"
  "skromno :>"
  "ba li go?"
  "stia s tea piramidi faraoni be, dai praim pachki!"
  "problemi li imash?"
  "ako iskash moga da ti dam toaletna hartia da se uspokoish malko"
  "az she vikna tia ot hei i she im kaja kvi gi byrkash nezakonni i she vidish ti!"
  "niaa takiva filmi"
  "ama ti verno li?"
  "toziiiiiiiiiiii raaaaaaaaaaaai vodi v aaaaaaaaaada.."
  "smeni povedenieto ili she vidish irc prez kriv makaron"
  "dai da izqdem lainoto na mira!!!!!!"
  "iskam te!"
  "iskam da mi padnesh na kanapeto v hola, ili da te ... v kilera na tymno .. "
  "ne sym umrial sha znaish.. za tvoita sliva mirizliva .. sha znaish!"
  "ebah ti maikata kirliva.. sys moita krastavicka kriva"
  "fuck the shut up!"
  "uuuuuuuu"
  "eeeeeeeeeeeeeeeeeeeeeeeeeeeee"
  "ami..."
  "neska gleda li se v ogledaloto?"
  "vij che oshte imash laina po ustata!"
  "imam tuka eno presno laino... halal da ti e!"
  "grrrrrrrrr"
  "ama ti mai naistina ne znaesh kvo e laino?"
  "tebe mai skoro ne sa ti pravili klizma?"
  "imash li pompichka? iskam da si napompam gyza i da ti se izpyrda moshtno v chovkata!"
  "odi iaj kompot"
  "she kaja na Jordy da te uhape!"
  "ah, da niamashe v teb takava prostota, shteshe da e chudna nashata igra!"
  "ti li she mi kajesh!?"
  "ama kaji si kvoto mislish za mene, kvo.. sram li te e?"
  "celuni me!"
  "zadnika ti moje li da kazva 'Aaaaaaa' ?"
  "marsh be, merishat ti krakata!"
  "tva zvuchi gordo"
  "lainoQd!"
  "iad li te e?"
  "stegni se de, kvo se speche :>"
  "stava interesno"
  "licemer!"
  "v detskata si vyzrast znaeshe li che ot tebe she izleze takava utrepka?"
  "ku ta kovna s teslata samo na mastul she mi stanesh.."
  "ma ne me mastulosvai be"
  "ia ne govori tolkova ednosrichno che stava banalna cialata istoria"
  "az se prerodih"
  "heh, kalyf!"
  "abe da znaesh sluchaino kolko e golqma chernata dupka w linsuxa? sta prata taam da znaeh ... mv klamer /dev/null"
  "iskam da te chukam v tzyfnalata ryj.. ili neshto takova :>"
  "tolkova li samo znaesh?"
  "iskam zadnika ti uhilen do Ushi... i da go natypcha s krUshi :>"
  "znaesh li che vengador mnogo ti e nabral?"
  "brb"
  "ama tuka niama domati, tva e knijarnica!"
  "meh, leke silistrensko.."
  "byllllllvoch.. pumia.. blia.. ueeeeeeeeeee.. "
  "ы9 = 3 :>"
  "taka, taka.."
  "i posle?"
  "fantazirai si.. :>>>>"
  "                                      .        "
  "neznam laino li si kvo si ama mnoo smeshno mi staa ot tebe :>>"
  "ne taka, ako obichash!"
  "ur welcome"
  "abe .. jivei nebrejno dokato umrat sysedite! pa kato umrat she te pokanat na pogrebenie i pak she piesh !!!"
  "mastika forever!"
  "ih, chak me zasyrbiaha testisite.. :PP"
  "mda"
  ".. i shte ti go podam tvyrd"
  "miaaaaaaaaaaaaaaaaaaaaaaaaaaaooooooooooouuuuuuuuuuuuu"
  "eeeeeee tva ti li si be, bassi ne moa te poznaia!"
  "slusham!"
  "po-leko da ne lapnesh na CrazyIns dyrvoto.."
  "tova ne me zasiaga"
  "i love my lame ass!"
  "za tebe sichko mi e ot iasno po-iasno be, nali ti chetoh dosieto.."
  "ti za kvo mislish che toaletnata hartia e dvuplastova? nali edinia plast ti otiva direktno v dosieto"
  "da ne bi da iskash da ti gledam na laina?"
  "narichai me mastulien... obicham francia, parij.. frenska liubov.. btw iskash mi teglish edna svirka?"
  "eh, da mojeshe da te chue chichko Lenin.. shteshe da se zavyrti v groba!"
  "ee, nedei se pritesnqva be.. ti ot maitap ne razbirash li?"
  "pusni si CNN byrzo! davat arestuvaneto na Dos!"
  "jalka utrepka.."
  "kaji be bokluk!?"
  "ti seriozno li po cial den na irc visish? maikaaaaa.. triaa si s mnoo komplexi znachi.."
  "oranjevite maiki s oranjevi dechica..."
  "az sym samo edin iunusha beden.."
  "lele odeve kvo laino izsrah.. nee istina.. tochno na kur prilichashe.. i kak placheshe za tvoite ustenca"
  "iskash li da ti kaja edna publichna taina? ti si seksualen invalid.."
  "baaaaaaaaa, she mi opadat kosmite ot gyza oshte malko ako te slusham!"
  "niama znachenie.."
  "i?"
  "((-:"
  "ne dyrpai diavola za opashkata che toku vij ti se izsral otgore... e togava ne ti zavijdam naistina .. :>"
  "lemur"
  "vijdam li kolebanie v ochite ti ili taka mi se struva?"
  "ibi my kopili ibi my, shot sym lekomislina.."
  "qm i piq, iby i biq"
  "rozovoto ili sinioto?"
  "abe bira sex i CSKA!"
  "tc tc.. zavi mi se sviat na svetofara!"
  "dreme mi na pumpala"
  "vkisnaha mi se lainata ot tebe"
  "a ekskrementi s luk iskash?"
  "az mastul li sum ili uiova glava?"
  "mm.. ia ela da mi pokarash trotinetkata!"
  "biva li taka?"
  "ne e tva tochnata duma spored men"
  "imash li snimka?"
  "shut your mouth!"
  "mnogo sladkodumno govorish, chak bybreci me zaboliaha.."
  "po-zdrav za tebe po fm+"
  "te has mi kola"
  "hoi pitai katil ;-)"
  "o`ti n`eba putkata maina"
  "mm.. tiiii... dovechera kak si s vremeto?"
  "are stiga zadava typi vyprosi!"
  "ti mene za typak li me mislish?"
  "aaa-se-ga-o-ba-de-ni-q-na-molq-drugar-ka-taaaaaa"
  "nachi zavivash naliavo, otivash do edna niska sgrada, stigash do sinia vrata, natiskash edno sluginche, pokazva se edno butonche i vikash dai dve milicionercheta za chicho banichko"
  "dai da zamesime nekoi ot kanala.."
  "chu li nai-novia sluh za lanzz?"
  "be neshto mai ne sym na kef neska ..."
  "shto ne minesh da piem po kafe s raiber"
  "ai da pushim po cigara i posle pak she govorim, ok?"
  "abe ti s windows li si?"
  "vnimavai sha kaja da te prouchat tebe az sti kaja na tebe.."
  "tuka ima .. tuka nema .. ? kyde e topcheto"
  "ako nekoi ti se struva pros - ne govori s nego"
  "vij kvo, ako prodyljavash da mi govorish she te sloja na ignore"
  "ia se pogledni kak smyrdish, tva da ne e opit za plagiatstvo - mastul -> smyrdul?"
  "ku iskash da ubiesh pylkovodeca - ubii pyrvo konq mu"
  "abe vie se smeete i nie se smeeme ama nakraq she si smenime rolite.."
  "koito kol ostri na drug mu vliza v gz"
  "i glupakyt e umen kogato mylchi"
  "po-dobre prelystena i izostavena, otkolkoto zapochnata i nedovyrshena :)"
  "btw naesh che davat 4 muri na cenata na 3?"
  "ne .. s tva e kofti.. chai she mislime neshto prosto..."
  "spokoino be.. ne byrzame :))"
  "aaa .. kak beshe ..."
  "aaaaaaa .. neshto noo si lagnat mai?"
  "ia pitai nekoi ima li da mi dade ena cigara"
  "ogynche?"
  "ei neska me globiha v tramvaia deba.."
  "d`eba vash`ta mama!!!"
  "i ti li she me biesh kato demond i kirov?"
  "q trai da ne te floodna.. che she isfyrchish kat izpyrdqna tapa iz gyz"
  "hahahahaa... .mnoo smeshno.."
  "bleep"
  "happhaite phaphli"
 ":))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))"
  "shto ne mi smuchesh lukankata .. "
  "when tha shit goes down ... "
  "i will fly to the moon and back if you`ll be my babe.."
  "smyrdyt miiiii... llainataaaaaaaa... debeliteeeeeee.. llainaa.. "
  "ne mislish li che e vreme da si lqgash veche a?"
  "nqkoi ima li chasovnik?"
  "hmm, tva oste ne bqh go chuval"
  "ping meeeeeeee!!!"
  "ako iskash tel. 760725 obadi mi se utre sled obqd:))"
  "ma ti kvo, da ne me svalqsh a?"
  "q da si haresam nakoq ot kanala da si lafime.. kaji .. znaesh li niakoi zdrav pich?"
  "mlaad pojarnikaaaaaar... - tva znaesh li otkyde e? :-)()"
  "aaaaaaaaaah... crushhhhh..."
  "beibeeeeeee ... meibeeeeeeeeeeeeeeeeeeeeeee.... "
  "ti slushash li cypress? ili onyx?"
  "taka se setih za metalskite godini.. lelei kvo beshe ... piene iako ... piene. mastika... metallika .. piene .. metalika .. i tia tri neshta .."
  "basi,  trqqshe da hodq da pieme v fugi.."
  "obache tva CNN e mnoo gotino.. nali? :)"
  "btw coca cola sa kupili pepsi .. i te defakto si ostavat, ama dalaverata si e chist monopolizym.. az bih gi sydil kakto si go zaslujava i willy gates III .. ma tva e .. be zaebi"
  "izleze nekva beta na windows 2000!!! begai na www.microsoft.com da teglish, pyrvite 5 dni e free!"
  "a, otivam da si vida maila.."
  "na maika ti v ustata zlatni zybi ima li?"
  "iskam az kogato sym do teb, o mili.. kogato nad zemqta padne mrak.. s shishe ot bira da me iznasilish .. ili pyk s shishe konqk"
  "obicha me .. ne me obicha .. obicha me .. ne me obicha .. obicha me ..hmmmmmm .. obicha me :)))))"
  "hmm.. da viime sa ..."
  "nachi ... hehe .. ne .. ako ti kaja ... po-dobre da ne znaesh .."
  "hahahahhahahahahahahahahahahahahahahahahahhaahahahahhaahahahahhahahahahhahahahahahahahahahahahahahahahahahhaahahahahhaahahahahhahahahahhahahahahahahahahahahahahahahahahahhaahahahahhaahahahahhahahahahhahahahahahahahahahahahahahahahahahhaahahahahhaahahahahha"
  "tva she floodne kanala be!"
  "abe .. ti ot mlados li si? shot az sym ot lulin.. i bashta mi e ot lulin .. i. maika ti!"
  "neska si kupih fototapet na Kasandra"
  "abe gleda li vchera Mari Amor.. shot go izpusnah/ da mi razkajesh kvo stana"
  "nekoi da mi dade 200 leva na zaem da prasnem ena svarka?"
  "uphphphphphphphphphphphphphphphphphphphphphph"
  "gorkia mastul, az na negovo miasto shtiah ili da ubia bashta si ili da si podam Ustavkata.."
  "chakai da obyrna CD-to"
  "abe .. she hoime li v domino pak?"
  "ti mai ne me pomnish, a az tolkova mnogo se nadiavah ... "
  "dai si ICQ-to che na tva irc typotiq ot sqkyde."
  "kvo she kaesh za edno cyber sexche?"
  "samo levski!"
  "samo cska!"
  "slavia rulz!"
  "nema moe nema tvoe sichko e beroeee"
  "az pa ne sym takyv komplexar kato tebe :)"
  "ama sym prostak samodovolen :)"
  "abe toia pianist me nauchi da qm sladko .. blah.. "
  "ela v sybota v nas, CrazyIns she prai palachinki da ia gledash kak i podskacha gz :)"
  "ti nqmashe li da me cherpish edna bira ot onq pyt?"
  "danyk sgradi i smet za 1999 godina ot dnes pishe vyv 25 chasa"
  "ba li mu mamata? veche izprostiavam.."
  "tebe koga ti beshe rojdenia den"
  "moesh li da prydnesh s prys v gz?"
  "trqa poveche laina da ima .."
  "aa .. samo laina bati... "
  "abe drishlio!"
  "ako poglednesh krygovrata v priradata ot opredelena gledna tochka stigash do tam, che nie vsichki proizlizame ot lainata: laina->mikroorganizmi->pochva->rastenia..."
  "iskam da napisha visoko v nebeto obicham jivota s laina"
  "chai da ida da  nareda edin tetris"
  "bah.. odeve prydnah kopele ... merishe na zele.. oshte ne moe se provetri.."
  "ti mani .. mi vchera kato srah posle kenefa beshe ... abe se edno kofa s razvaleni qica :)"
  "basi .. svyrshi mi toaletnata hartia.. she minavam na samobrysnachki.. po-eftino e :)"
  "gotino e kato imash raztroistvo kak pryska iz cialata toaletna chinia :)) basi kefa e :))"
  "a imashe edno za ostrovyt na lainovishtata .. tam imashe nekyv det nameri nahodishte na laina .. ma whatever .. nai-got beshe kato pochna da kopae i tva izrigna kato vulkan .. laina iako, zalia go celia :)))))))))"
  "pochva da mi se gadi ot laina veche, samo za tva govorite sichki"
  "ma gledash kato nasran :))"
  "obeshtavam ti edna opakovka.. samo da patentovam formulata tabletki raztvorimi laina s dyh na chesyn, praz ... moje i s dyh na laina ako iskash :)))"
  "otishli fugi i sodo na restorant.. sodo: 'kyf e specialiteta?' kelnera: 'laina s praz' sodo: 'daite ni 2 porcii' fugi se obajda: 'ednata ako mzohe bez praz che sym na sreshta posle"
  "abe .. moesh li s gz si ednovremenno da seresh i da svirish na fleita? :)"
  "moia tatko vednyj obeshta .. da mi kupi 5 kofi s laina ......"
  "kravataaa dnes ne sraaa.. niama kvo da iadaa...."
  "laina li da qdem ili da sa ibem?"
  "re"
  "mnoo iako shteshe da e ako botovete hodeha do kenefa da im nadnichame pod vratite da im gledame zadnicite :)"
  "i vse pak she se okaza prav...nali?"
  "ti kolko pyti na den hodish po golqma nuzda?"
  "i da si pusnesh vodata kato se izseresh..."
  "dris dris..."
  "  I A  mastul2.tcl (Modified)       Row 697  Col 4   "
  "im artses an hsarab og ad i atanial hsedq im ad"
  "abe kato se zamislia da pishesh na obratno e lesno, ama kvo li she e da seresh naobratno (ne s gz nagore, a da seresh navytre) .. sigurno kato pederastia... "
  "chuvstvam se kato naebana jena .. basi kefa mi e :))"
  "q si obrysni mustacite ma!"
  "napomniash mi za onaa fliorca ot 3tia etaj :)"
  "rygai laina v boba s udarenia na A"
  "ama sutrin kato niamash cigari i toplo kafence .. basi .. zapek :("
  "auuuuu... chak tuka go useshtam, zabrail sym da si pusna vodata!"
  "ami .. laina"
  "dai she fanem semeistvoto na TReX.. sinyt za tebe, dyshteriata za sichki ostanali :)))"
  "i vnimavai da ne iadesh chereshite s kostilkite,che posle kato seresh si ebalo maikata she si razcepish analnoto otverstie"
  "mutrata kaza che ne e bash taka ama aide :)"
  "az v sobstvenite si laina ne viarvam, pa v diavola li?"
  ".. ama ima bezshumni prydni.. te sa nai-opasnite.. naesh kak smyrdyt .. ne se trae posle 2 chasa"
  "a vednyj CTAMAT se izsra v supata, ne beshe sral ot 1 sedmica niakyde .. i ne zatvori vratata na kenefa.. posle poznai kvo stana.. vsichki drujni se kachiha na gornite etaji.."
  "nie kato malki si palehme prrydnite .. ti praveshe li go? :)))"
  "3 dni boi, ebane i nikva televizia.. e tva e istinata.."
  "malko se pie v taa dyrjava .. mdaa.."
  ".. gol v baniata .. s ryce v djobovete.." 
  "shefeeeeeee.. tyrsiat te po lainofona"
  "haide v primorsko haide v burgas, site kenefi bachkat za nas.."
  "tri + tri = na shes.. 1 + 1 = na laino.."
  "chete li si horoskopa za neska? ili da ti go procheta?"
  "deba sichki ste edin dol laina..."
  "dai da izmislim neshto za chalga tam.. iza putki.. :)"
  "vuina ti.."
  "abe i na teb sa ti ebali maikata .. kvo se praish sa :)) ako ia biaha upushtili niaashe da si tuka da mi dudnesh gluposti .."
  "kvo za chalgata?"
  "oti?"
  "BHG SUX!"
  "ti li vlizash prez *!*@mastul.me.eba.v.gz.com ?"
  "a na bas che ot 4 vlizania v moia kenef 5 she se naseresh"
  "sa sh se poraztypchem i she izmisla neshto :))))"
  "ih ma sym typ nali :))))"
  "da ti go nachukam :)"
  "lainar"
  "eh sine sine ... "
  "ma ti izleze li ot bolnicata?"
  "da beshe sipal po edno whisky veche a?"
  "e tva e.. kato moito gadje drugo niama .. ibe sy, prai svirki zdrao.. tyrpi a laina .. kvo poiche iskash?"
  "da be, setih se :)))"
  "who are you?"
  "da be.. problema na jenite ot FMI ne e che sa grozni, a che na 2rata godina ochvash da gi haresvash"
  "ti naistina li mislish che tolko lesno se praviat laina? se edno da byrkash alva s masylce a? .. mneeee , greshish batka"
  "\[SESIL(cool@ppp2.bulnet.com)\] domashen telefon 77 48 45^M SESIL(cool@ppp2.bulnet.com)\] tursi me kato sisi nai dobre v subota sled 6^M    e skii kva e taa prodajna kuchka smotana s fizionomia na pepelnik"
  "31-48-06 31-61-97 - tva sa telefonite na sandra.. govori si :)))"
  "kvo mi bibikash samo kato kutrovski be :)"
  "37 08 43 - e tva pa e telefona na b|tch ili se|ena ili bibi|ate ili nekvi takiva se smotani nickove :)) ani se kazva .."
  "iskam da ima marshrutka ot razsadnika do je.ka. borovo :)"
  "veche moga da sviria na duduk .. ili tam kaval li kvo beshe :)) skoro i na lainimba she sviria.."
  "q kaji oshte neshto da se seta be"
  "abe skii na kanala se napylnilo s novi pichki .. dai da hoim gi zabivame tokuvij sme maznali malko da poibem.."
  "vashte znaiat li za cigarite?"
  "if ($hozt !~ /[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/)  i blabla ... "
  "glupostta nikoga ne svyrshva dotuk unless defined($dotuk) :)))"
  "oh tia dvete Gabby i ophellie kak she gi shibam leleiiii.. kato zverove she se ebeme ti kazvam"
  "eiiiii plashim se kopele!"
  "nee istina .. "
  ".. razbirash li .."
  "balo si maikata"
  "ili taa jazzgril li beshe .. jazzkuchka li beshe kotka li beshe.. ih da mi padneeeeeeeii.. she i skysam trytkata .."
  "ma taa plondi nema nikvi ... deba :))))"
  "a skii lorena-morena... niama i neia koi da ia oprai .. pak az she triaa si prejalia blagoslovenoto dyrvo"
  "ako uspeesh da si navresh cheshmata v gz pusni toplata voda i slushai jamiroquai .. tva mu se vika 'direct clisma'"
  "ti li si sledvashtia be? :)) hehe"
  "tuka s fugi mislehme neshto za pianist.. ama e mnou gnusno .. niama da ti kazvam, che shti potekat lainata prez kracholite napravo"
  "ei toa fugi e basi perveznia pedal smotlio da go eby v neshtastnika.."
  "blah.. ot tebe i ot tia skateri she se izdraifam kato valentin v krychmata.."
  "ti kak si s po-specialnite matematiki, che imam da pisha kursova zadacha na C programa da smiata obem i lice na ploshtta na laino, pri podadena goleminata na gz mu, sechenieto i hranata pogylnal prez poslednite 26 chasa"
  "be ti prilichash na lucy be .. nishto ne ti se chete .. i tia taka .. hodi igruhti .."
 "moe si govorish kvoto iskash, ma az se imam za edin ot nai-pechenite botove uka, gz si zalagam!"
  "ma kvo mi se kefish kato ciganche v taxi?"
  "lelee, ako te fana shte raznasqm kato praskachka iz loze..."
  "vnimavai che she go otnesesh kato premraznalo ciganche - vatenka"
  "moje i veche da ne e aktualno ama edno vreme (po babino vreme, na taia yshtata baba deto goneshe fashistite s tvoite  lafove) takiva kato tebe gi atvariaha po tvu-ta i zatvori.. aa maha"
  "abe ti ako slushash fugi she vlezesh v zatvora, a ako slushash pianist - nqma a izlezesh ot tam:)"
  "she piinesh li edno kafence?"
  "znesh li , snosti te synuvah ...kak dvamata s tebe...nali razbirash....si izahme shkembetata i si byrkahme v dupetata..."
  "iskashe mi se da te vidq kolko struvash na jivo..."
  "tuka mnogo te biva mai , ama she se vidime v nekoi kenef..i she ti sekne ainoto"
  "ama niama otyrvane ot mene a? :)))"
  "twojta mama d`eba :))"
  "skiwash li - i w kazarmata ne me shtat... e twa e :))"
  "ela nasam, molq!"
  "mi izduhai go be :)"
  "kaji na onaia zaspa za sreshtata"
  "mi pomoli niakoi drug da go izduha togaa che men me mrzi :)"
  "kaji muuuuuuuuuuu"
  "she hodataistvam za teb pred уї±ёїІС Ѕб©Ў««»°буїІСЅї"
  "ako edin chowek ima dwa e-maila, kak da ti gi razdelq?"
  "mojesh li da se celuvash sys zatvoreni ochi?"
  "a mojesh li da seresh s vyrzani ochi? :)"
  "az ne piq be "
  "fanah te da lyjesh! fanah teeee!"
  "aa.. zadryj si go.. az ne sym alchen :))))"
  "napravi si test za bremennost.. che ot tia laina ...."
  "trqbwa da se pusne poredniq bulk...."
  "e ubu de :))))))) razbrahme che si pedal :))))))"
  "biraaa! biraaa! what has become of you?"
  "nali ti kazah che dnes sym v zatymnenie"
  "ooo slyncho :))))))"
  "obich moia!"
  "oooooooonnlllllllyyyyyy yyyyyyyyyooooouuuuuuuuuuuuuu.........."
  "ne me kefish be"
  "naesh kva e razlikata mejdu gospod i DJ-a? :))"
  "da be :) koito tyrsi namira .. taka kazvat pone.. i koito sere sichko Usira ))"
  "'bal sym i PCtata 'bal sym i chudoto :)"
  "mjetnesh kurosh naramosh .. pojebesh pobjegnesh.."
  "Trista Liudmili v gyzy ti!!!"
  "'640K sought to be enough for anybody.' - Bill Gates, 1981"
  "shveps rulez .. i pecheni jenski zadnici na sredizemnomorsko slynce :)))"
  "baba ti rulez :)))"
  "nali s bratofchet ti pederaza ne q obichahte mnoo-mnoo ;]"
  "eh predstavqm si vi kak se greete edin-drug ;]"
  "moje li da te pipna po dupeto?"
  "iskam da te stisna mejdu krakata :)))"
  "az sym pederas, ama i ti ne padash po-dolu ot mene :)"
  ".. mi taka ili inache sym liubimeca na vsichki :))))))))))) shto da ne si raa i az malko avtochetki :))"
  "dveeeeeee lainaaaaa... ne mogat da se sleiat v dveeeee lainaaaaaaaaaaaa .. ne ogat da se sleiat v dveeeeee lainaaaaaaaaaa......"
  "haide pokaji mi za kakvo stavash :))) iskam da ti se kefa "
  "v teb neshto me vyzbujda. . i me izbiva na sadizym... iavno seresh mnogo ynki lukavi laina :))"
  "e shto pa purata na clinton, po-dobre moita pura... botska pura naesh li kvo  , a ?"
  "pratih ti mail"
  "taka ne stawa - trqbwa da mu se kreshti po-silno"
  "az otivam da sera..."
  "abe baby, kolko pyti trqq ti kaza che te obicham!?"
  "taka si mislish samo ti i grupa syvetski ucheni..."
  "mezdudrugoto , mina li ti zapeka ot onq den?"
  "imalo edno vreme edna chervena shapchica.....taq prikazka znaesh li q..."
  "ti pa kvo pak se izkazvash nepodgotven a..."
  "vinagi mi idvat sveji idei v kenefa :))"
  "a mnoo e got da seresh v kenef s dupka samo ... strashno e .. kato padne to i copva i pryska zdravo .. .taka em se kefish na sounda em ti mie gz i niaash ijda ot toaletna hartia"
  "bih si legnal s tebe, ako znaeshe pone neshto za cvetovete na esennite laina "
  "triabva da opitash da risuvash s gz si .. shti haresa .. natiskash se po porema i stava kato temperni boichki .. i zbuka e gotin :))"
  "to vednyj kato zavaliat lainata.. e togava glei showto.. she gi vidim tia deto gi e strah ot laina :))"
  "abe sluchvalo li ti se e da iadesh laina i da seresh sladoled? :))"
  "brysni si redovno kosmite okolo dupkata na gz, shot ako ti se spletat ne moj da seresh, kazvam ti kato cedka stava.. basi ujasa .. posle 2 chasa ne moj go izchisti"
  "ako hvana zlatnata ripka sh si porycham pozlatena toaletna chinia s laina ot div poliaren slon"
  "predstaviash li si samoletite i avtomobilite da se zadvijvaha s laina .. eiii togava ot auspusite kvo shteshe da izliza a? :)))"
  "ako nosish gashti nomer 5 - nosi nomer shes .. vinagi s edin po-goliam za da ne izpada kato se poakash, a ako sluchaino ebemti ne se naseresh da ti se provetriava.. air condition, nali razbirash.."
  "mi az ne mislia taka (tva v procesa na pisane triaashe da e malko po-zabyrkano taka kato laina s govna.. )"
  "shto si mislish, che ti viarvam?"
  "ako te  fana za sex dryjkite she ti napylna dupeto s liubov - demek shti nabutam edin .... v gz i shte floodna sys zapetaiki"
  "davai idei az she gi lainificiram..."
  "brykni v kontakta i skii kak shti nastryhne gz"
  "vij go toa pochna da rysi gluposti kato da sere bezrazborno na ploshtad makedonia"
  "mda.. typi raboti.. iztyrkani .. kato gyz sled iako srane s shkurtka"
  "btw (ama toia pyt ne e kakto obiknoveno) odeve izsrah.. ne .. aide ne izsrah . ili daje mai e po-dobre da ne ti kazvam kakvo mi izleze ot zadnika v kenefa :))"
  "ooo, liubov moq, az bez teb ne moga"
  "ebati sa perverzii ne moa se seta ama taka kat te gledam bih naprail neshto za ovlajniavaneto na ekrana si :))"
  "tolkova li sym prost i cinichen?"
  "ako mi raboteshe dcc-to shtiah da ti prata moia snimka po bikini da vidish kak mi visat kambankite otstrani.."
	"az sum bot i shte vi buda zabavlenieto za dnes"
	"na sichko nosq na t-burd nosq na amd nosq na apple nosq sichko nosq ..."
	"basi perverznoto pleme ste vii decata"
	"pak li sha marsuvash s mladi chaterki"
	"tiho sa ;p"
	"neka si4ki da vidqk kyf si miskinin"
	"are izvadi mi kirlivite rizi sa pred sichki"
	"ne nam"
	"az kako da napraq"
	"shtoo..."
	"neshta nikogo da poznavam"
	"ama kaji, shto de"
	"abe ei tui"
	"heh"
	"stiga s glupostite"
	"obicham da rabotq bez zaplashtane"
	"adi da odim da piim po 2-3 bira dovechera"
	"drugata sedmica"
	"nali naish che sym hiper silen"
	"drugata sedmica sum na pochifka"
	"taman sa chudqt kfo da praqt"
	"adi marsh na selo tuka sme samo grajdani :)"
	"kaji neshto umno"
	"basi se gluposti govorish"
	"po prozzd ot tebe ne sum hakval sha znaish"
	"tiho sq cheta avtobiogtafiqta na tbyte ..."
	"stiga si ma botval che sha ti skacham na ushite"
	"hi a/s/l pls"
	"gagagaggagagagaga"
	"lq lq lqlqqq lqq"
	"q podai ton za pesen ..."
	"fuck you stupid user@mail.sx"
	"lovq kotki kucheta i drug selskostopanski edur divech"
	"istinata si e istina"
	"edin put i ti da ne izlujesh"
	"ti si v tejest na obshtestvoto"
	"i ti sux"
	"i ti r0x"
	"sichki sme si super :)"
	"i az ta haresvam"
	"po prozd i ot mene si be"
   }
  }
 {  
  {"*zdrasti*" "*zdravei*" "*hello*" "hi*" "*hey*"} {
	"Heyy, what's up $nick"
	"y0 $nick"
	"zdrastiii"
	"mahai sa be $nick, ne mi trqbvash tuka"
	"mahai sa ne moa ta gleam vechi :p"
	"zdr pi4 :)"
	"aide marsh"
	"gruh :)"
   }
  }
 {
  {"What time is it?" "*time*" "What is the time?" "What's the time?" "Anyone have the time?"} {
   "$nick, it's [clock format [clock seconds]]"
  }
 }
{
 {"*4ao*" "*4a0*" "*bye*" } {
  "Ai mai sa de!"
  "eee sa setish sa mahnish"
  "$nick 4upka fe abuser"
  "bye bye sar4itze"
  "$nick she mi lipswash"
  "ei $nick da ma sanuwash w oskadno belio"
  "DowiJdane"
  "Edin pRoZdtak po Malko;)"
  }
 }
{
 { "*a/s/l*" "*na kolko si* " "*asl*"} {
   "18 f vn"
   "i TolkOz nqmam"
   "ei pedofil malak"
   "pyrwo ti "
   "asl = another stupid lamer"
  }
 }
{
 { "*eba*" "*sex*" } {
   "she ebesh ako ti pusna"
   "golqm eba4 sa izwadi i ti fe"
   "she ebesh mara shepowa s 5-te badjaka"
  }
 }
{
 { "*kurvo*" "*ku4ka*" "*kurwo*" } {
   "kurwa e maika ti !"
  }
 }
{
 { "*kwo praish*" "*kvo prawi6" "*kuklo*" } {
   "za tebe si mislq "
   " 4opkam walna"
   "iba lubopitni"
  }
 }
{
 { "*ebesh*" "*ebe6*" } {
   "kak da gi eba fe pROzd da wiJdash _)_ m/y krakata mi"
  }
 }
{
 { "*borish*" "*tursi*" "*bori6*" } { 
  " $nick Trursq maika ti... tq kade e i  ko prai ??"
  }
 }
{
 { "*ops*"  } {
    "You DId It AgaiN suCkaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  }
 }
{
 { "*psl*" "*pls*" "*plz*" } {
     "nq kwo mi sa molish az sam nepreklonna"
     " $nick mri we !"
     "nqma kwo da mi sa molish da ne ti prili4am na maika Teresa?" 
  }
 }
}

# Set the next line as the channels you want to run in
set ai_chans "#channel1 , #channel2"
bind pubm - * pub_ai

putlog "speak.tcl by www.mIRCbg.net loaded"

proc pub_ai {nick uhost hand chan arg} {
 global ai_data ai_chans botnick
 if {(([lsearch -exact [string tolower $ai_chans] [string tolower $chan]] != -1) || ($ai_chans == "*")) && (![matchattr $hand b]) && ($nick != $botnick)} {
  foreach block $ai_data {
   set triggers [lindex $block 0]
   set responses [lindex $block 1]
   foreach trigger $triggers {
    if {[string match [string tolower $trigger] [string tolower $arg]]} {
     putserv "PRIVMSG $chan :[subst [lindex $responses [rand [llength $responses]]]]"
    }
   }
  }
 }
}
